name: forgot_my_password
publish_to: none

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  component_library:
    path: ../../component_library
  flutter_bloc: ^8.0.1
  flutter:
    sdk: flutter
  user_repository:
    path: ../../user_repository
  form_fields:
    path: ../../form_fields

dev_dependencies:

  mocktail: 0.1.4

  flutter_lints: ^1.0.4

flutter:
  uses-material-design: true