name: component_library
publish_to: none

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1
  flutter_svg: ^0.22.0
  auto_size_text: ^3.0.0-nullsafety.0

dev_dependencies:

  mocktail: 0.1.4

  flutter_lints: ^1.0.4

flutter:
  generate: true
  assets:
    - assets/
  fonts:
    - family: Fondamento
      fonts:
        - asset: assets/Fondamento-Regular.ttf